site_name: ELISA - Open Source Engineering Process
repo_url: https://github.com/elisa-tech/wg-osep
site_url: !ENV [BASE_URL, https://osep.elisa.tech/]
site_dir: public

theme:
  name: material
  logo: images/elisa-logo.svg
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Open Sans
    code: Fira Code
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top

extra_css:
  - stylesheets/elisa.css

use_directory_urls: false

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.pathconverter:
      absolute: true
  - pymdownx.tilde

nav:
  - ELISA: https://elisa.tech/
  - Directory: https://directory.elisa.tech/
  - OSEP:
    - Home: index.md
    - Interference Scenarios (ARM64): 'Interference_Scenarios_for_an_ARM64_Linux_System.md'


